language: cpp
compiler:
  - g++
addons:
  apt:
    packages:
    - cmake
    - libboost-test-dev
    - g++-5
    - gcc-5
install:
  - export CXX="g++-5" CC="gcc-5"
script: cd build && cmake .. && make -j4
